import type { MotorPart } from '../store/useDigitalTwinStore';

/**
 * Canonical catalogue of selectable motor parts.
 *
 * `id` must match the mesh name as it appears in the GLB scene graph.
 * We use a broad match strategy in InteractiveModel: if a mesh's name
 * contains any of these IDs (case-insensitive), it is treated as that part.
 *
 * Future milestone: replace placeholder descriptions with live diagnostics
 * sourced from the ESP32 telemetry stream.
 */
export const MOTOR_PARTS: MotorPart[] = [
  {
    id: 'body',
    name: 'Motor Body / Housing',
    description:
      'The primary structural enclosure of the motor, manufactured from cast aluminium alloy. Houses the stator windings, rotor assembly, and provides the mechanical mounting interface for all external components.',
    purpose:
      'Mechanical protection, electromagnetic shielding, and thermal dissipation pathway for internal heat generated by stator copper losses.',
    futureTelemetry: ['housing_temp_c', 'vibration_rms_g', 'acoustic_db'],
    futureDiagnostics: ['bearing_wear_index', 'insulation_resistance_mohm', 'winding_fault_code'],
  },
  {
    id: 'vent',
    name: 'Ventilation / Cooling Fins',
    description:
      'Radially-arranged aluminium cooling fins integrated into the outer housing surface. Works in conjunction with the shaft-mounted cooling fan to maintain safe operating temperatures under continuous load.',
    purpose:
      'Forced-air convective cooling to maintain stator winding temperature below Class F insulation limits (155 °C). Critical for sustained duty cycle performance.',
    futureTelemetry: ['inlet_air_temp_c', 'airflow_m3_per_s', 'fin_surface_temp_c'],
    futureDiagnostics: ['airflow_obstruction_flag', 'thermal_runaway_risk_level'],
  },
  {
    id: 'bolt',
    name: 'End-Bell Mounting Bolts',
    description:
      'Stainless steel hex-head fasteners (M8 × 1.25 pitch) securing the end bells to the motor housing. Torqued to manufacturer specification using calibrated tooling during assembly.',
    purpose:
      'Structural integrity of the motor assembly under operational torque and vibration. Prevents end-bell separation and misalignment of the bearing bores.',
    futureTelemetry: ['vibration_rms_g'],
    futureDiagnostics: ['fastener_torque_loss_flag', 'mechanical_looseness_index'],
  },
  {
    id: 'shaft',
    name: 'Output Shaft',
    description:
      'Case-hardened carbon steel shaft transmitting mechanical torque from the rotor to the driven load. Features a precision-ground keyway for positive coupling engagement and threaded end for locking nut retention.',
    purpose:
      'Torque transmission from electromagnetic field energy conversion in the rotor to the mechanical load (pump, conveyor, compressor, etc.).',
    futureTelemetry: ['shaft_rpm', 'output_torque_nm', 'radial_load_n', 'axial_thrust_n'],
    futureDiagnostics: ['shaft_misalignment_angle_deg', 'eccentricity_mm', 'coupling_wear_index'],
  },
];

/**
 * Retrieve a MotorPart definition by matching the GLB mesh name.
 * Uses a broad case-insensitive substring match to handle GLB exporters
 * that append suffixes to mesh names (e.g. "Body_001", "Bolt_L").
 */
export function findPartByMeshName(meshName: string): MotorPart | undefined {
  const lower = meshName.toLowerCase();
  return MOTOR_PARTS.find((part) => lower.includes(part.id));
}
